### ISSUE TITLE
Fix Nav Bar

### ISSUE THREAD

**Issue by kartikeya23** [MrCrook2711/Spark#1]
#Nav Bar
  * Should be fixed on top
  * Should fade in as scrolling down

**Comment by NirbhaySingh2711** [comment]
will try to work on the fade in.

**Comment by NirbhaySingh2711** [comment]
ab dekh le

**Comment by kartikeya23** [comment]
It does not work on my machine

Please recheck

**Comment by kartikeya23** [comment]
#3 Needs to be merged @MrCrook2711 
Then, this can be closed
